version: '3'

services:
  redis-master:
    image: redis:6.2.7-alpine
    environment:
      - REDIS_PASSWORD=password123
    networks:
      - watcher
    ports:
      - '6379:6379'

  cockroachdb:
    image: cockroachdb/cockroach:latest-v21.2
    networks:
      - watcher
    ports:
      - '26257:26257'
      - '8080:8080'
    command: start-single-node --insecure

networks:
  watcher:
    driver: bridge
