version: '3'

services:
  pulsar_manager:
    image: apachepulsar/pulsar-manager:v0.3.0
    ports:
      - '9527:9527'
      - '7750:7750'
    environment:
      SPRING_CONFIGURATION_FILE: /pulsar-manager/pulsar-manager/application.properties
    #volumes:
    #  - ./application.properties:/pulsar-manager/pulsar-manager/application.properties
    networks:
      - watcher
    depends_on:
      - pulsar
  pulsar:
    #image: apachepulsar/pulsar:latest
    #image built for arm64-linux / apple M1
    image: kezhenxu94/pulsar:latest
    container_name: pulsar
    ports:
      - 8081:8080
      - 6650:6650
    environment:
      PULSAR_MEM: ' -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g'
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
    command: /bin/bash -c "bin/pulsar standalone"
    networks:
      - watcher
volumes:
  pulsardata:
  pulsarconf:
networks:
  watcher:
    driver: bridge
